PN := "PNPM"
PNR := PN + " run"
PNX := PN + " exec"
TSX := PNX + " tsx"

dev: prepare
    {{ PNR }} dev

build: prepare
    {{ PNR }} build

publish: build
    {{ TSX }} scripts/gh-publish.ts

bootstrap: install-pnpm prepare

prepare: install-modules

[private]
install-pnpm:
    corepack enable
    corepack prepare pnpm@latest --activate

[private]
install-modules:
    {{ PN }} install
